---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-results
resources:
  - https://github.com/openshift-pipelines/tektoncd-results.git/config/overlays/base-only/?ref=dc54f48f6a1adfde07b923129db33aaa77a61213
  - namespace.yaml
  - api-route.yaml
  - watcher-logging-rbac.yaml
  - service-monitor.yaml
  - watcher-rbac.yaml

images:
  - name: ko://github.com/tektoncd/results/cmd/api
    newName: quay.io/pmacik-testing/api-b1b7ffa9ba32f7c3020c3b68830b30a8
    newTag: 2024-05-23_14-21-52
  - name: ko://github.com/tektoncd/results/cmd/watcher
    newName: quay.io/pmacik-testing/watcher-83f971ea227fb24157c0c699b824a628
    newTag: 2024-05-23_14-21-52

# generate a new configmap with updated values (logs api, db ssl mode) and replace the default one
configMapGenerator:
  - behavior: replace
    files:
      - config.env
    name: api-config
    options:
      disableNameSuffixHash: true
  - behavior: merge
    name: config-observability
    literals:
      - profiling.enable="true"

patches:
  - path: api-db-config.yaml
  - path: api-s3-config.yaml
  - path: api-sync.yaml
  - path: api-service-sync.yaml
  - path: api-service-tls.yaml
  - path: watcher-config.yaml
  - path: watcher-logging.yaml
  - path: watcher-sync.yaml
  - path: watcher-service-sync.yaml
  - path: api-kube-rbac-proxy.yaml
  - path: watcher-kube-rbac-proxy.yaml
  - path: watcher-service-patch.yaml
    target:
      version: v1
      kind: Service
      name: tekton-results-watcher
      labelSelector: "app.kubernetes.io/name=tekton-results-watcher"
  - path: api-service-patch.yaml
    target:
      version: v1
      kind: Service
      name: tekton-results-api-service
      labelSelector: "app.kubernetes.io/name=tekton-results-api"
