---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-results
resources:
  - https://github.com/openshift-pipelines/tektoncd-results.git/config/overlays/base-only/?ref=a602fb3e858f6a3195374d2175053db7e5db9f77
  - namespace.yaml
  - api-route.yaml
  - watcher-logging-rbac.yaml
  - service-monitor.yaml
  - watcher-rbac.yaml

images:
  - name: ko://github.com/tektoncd/results/cmd/api
    newName: quay.io/redhat-appstudio/tekton-results-api
    newTag: a602fb3e858f6a3195374d2175053db7e5db9f77
  - name: ko://github.com/tektoncd/results/cmd/watcher
    newName: quay.io/pmacik-testing/watcher-83f971ea227fb24157c0c699b824a628
    newTag: "pr715_b8a991a0a30b58c054feb628c56ab444ab8f0585_20240301-172358"

# generate a new configmap with updated values (logs api, db ssl mode) and replace the default one
configMapGenerator:
  - behavior: replace
    files:
      - config.env
    name: api-config
    options:
      disableNameSuffixHash: true

patches:
  - path: api-db-config.yaml
  - path: api-s3-config.yaml
  - path: api-sync.yaml
  - path: api-service-sync.yaml
  - path: api-service-tls.yaml
  - path: watcher-config.yaml
  - path: watcher-logging.yaml
  - path: watcher-sync.yaml
  - path: watcher-service-sync.yaml
  - path: api-kube-rbac-proxy.yaml
  - path: watcher-kube-rbac-proxy.yaml
  - path: watcher-service-patch.yaml
    target:
      version: v1
      kind: Service
      name: tekton-results-watcher
      labelSelector: "app.kubernetes.io/name=tekton-results-watcher"
  - path: api-service-patch.yaml
    target:
      version: v1
      kind: Service
      name: tekton-results-api-service
      labelSelector: "app.kubernetes.io/name=tekton-results-api"
